# Generated by Django 5.2.5 on 2025-09-02 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certified_by', models.CharField(max_length=100)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(max_length=50)),
                ('issued_at', models.DateField()),
                ('pearl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='main_app.pearl')),
            ],
        ),
    ]
