# Generated by Django 5.2.5 on 2025-09-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_craeted_at_pearl_created_at_auctionlisting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='issued_at',
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certified_by',
            field=models.CharField(help_text='Name of the certification authority', max_length=100),
        ),
        migrations.AlterField(
            model_name='certification',
            name='grade',
            field=models.CharField(choices=[('A', 'A - Excellent Quality'), ('AA', 'AA - Very High Quality'), ('AAA', 'AAA - Highest Quality'), ('B', 'B - Good'), ('C', 'C - Commercial Grade')], help_text='Standardized pearl grading system.', max_length=3),
        ),
    ]
