# Generated by Django 5.2.5 on 2025-09-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_certification_issued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='issued_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certified_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certification',
            name='grade',
            field=models.CharField(choices=[('A', 'A - Excellent Quality'), ('AA', 'AA - Very High Quality'), ('AAA', 'AAA - Highest Quality'), ('B', 'B - Good'), ('C', 'C - Commercial Grade')], max_length=3),
        ),
    ]
