# Generated by Django 5.2.5 on 2025-09-06 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_certification_issued_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='pearl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='main_app.pearl'),
        ),
    ]
