# Generated by Django 5.2.5 on 2025-09-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_certification_pearl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='pearl',
            name='image',
            field=models.ImageField(upload_to='pearls/'),
        ),
    ]
