# Generated by Django 5.2.5 on 2025-09-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_certification_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionlisting',
            options={'ordering': ['-created_at']},
        ),
    ]
