# Generated by Django 5.2.5 on 2025-09-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_auctionlisting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionlisting',
            options={},
        ),
    ]
