# Generated by Django 5.2.5 on 2025-09-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_auctionlisting_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='reserve_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
