# Generated by Django 5.2.5 on 2025-09-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auctionlisting_reserve_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='reserve_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
