# Generated by Django 5.2.5 on 2025-09-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auctionlisting_is_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='last_bid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pearl',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pearl',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pearl',
            name='shape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pearl',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pearl',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams', max_digits=8, null=True),
        ),
    ]
