# Generated by Django 5.2.5 on 2025-09-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_profile_location_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='start_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
